import { IRoute } from "@bluelibs/x-ui";
import "./i18n";

import {
  WORK_EXPERIENCE_LIST as BASE_WORK_EXPERIENCE_LIST,
  WORK_EXPERIENCE_CREATE as BASE_WORK_EXPERIENCE_CREATE,
  WORK_EXPERIENCE_EDIT as BASE_WORK_EXPERIENCE_EDIT,
  WORK_EXPERIENCE_VIEW as BASE_WORK_EXPERIENCE_VIEW,
} from "./config/routes";

export const WORK_EXPERIENCE_LIST: IRoute = {
  ...BASE_WORK_EXPERIENCE_LIST,
};

export const WORK_EXPERIENCE_CREATE: IRoute = {
  ...BASE_WORK_EXPERIENCE_CREATE,
};

export const WORK_EXPERIENCE_EDIT: IRoute = {
  ...BASE_WORK_EXPERIENCE_EDIT,
};

export const WORK_EXPERIENCE_VIEW: IRoute = {
  ...BASE_WORK_EXPERIENCE_VIEW,
};
